# Generated by Django 3.2 on 2022-05-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220502_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
